name: Race Results Cron Job

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  trigger-race-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Race Results Processing
        run: |
          echo "Starting race results cron job at $(date)"
          
          # Call the simple cron checker
          RESPONSE=$(curl -s -X POST https://zjqojacejstbqmxzstyk.supabase.co/functions/v1/simple-cron-checker \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" \
            -H "Content-Type: application/json" \
            -w "\nHTTP_STATUS:%{http_code}")
          
          # Extract HTTP status and response body
          HTTP_STATUS=$(echo "$RESPONSE" | grep "HTTP_STATUS:" | cut -d: -f2)
          RESPONSE_BODY=$(echo "$RESPONSE" | sed '/HTTP_STATUS:/d')
          
          echo "HTTP Status: $HTTP_STATUS"
          echo "Response: $RESPONSE_BODY"
          
          # Check if successful
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "✅ Cron job completed successfully"
            
            # Check if race results were processed
            if echo "$RESPONSE_BODY" | grep -q '"scheduler_result"'; then
              echo "🎉 Race results were processed!"
              
              # Extract processed count if available
              PROCESSED_COUNT=$(echo "$RESPONSE_BODY" | grep -o '"processed_count":[0-9]*' | cut -d: -f2)
              if [ -n "$PROCESSED_COUNT" ]; then
                echo "📊 Processed $PROCESSED_COUNT races"
              fi
            else
              echo "⏰ No races ready for processing"
            fi
          else
            echo "❌ Cron job failed (HTTP $HTTP_STATUS)"
            exit 1
          fi
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
